#importing numpy

In [1]:
import numpy as np

creating two dimentional array of shape (5,2)

In [2]:
array_5_2 = np.array([[1,2],[3,4],[5,6],[7,8],[8,9]])
array_5_2, array_5_2.shape

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [8, 9]]), (5, 2))

Transpose an array

In [11]:
array_5_2.reshape(2,5), array_5_2.T

(array([[1, 2, 3, 4, 5],
        [6, 7, 8, 8, 9]]), array([[1, 3, 5, 7, 8],
        [2, 4, 6, 8, 9]]))

using where method to filter

In [14]:
array_5_2 = array_5_2.T
array_5_2

array([[1, 3, 5, 7, 8],
       [2, 4, 6, 8, 9]])

In [20]:
np.where(array_5_2, array_5_2 < 3 | array_5_2 > 7, 0) 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [18]:
array_5_2 > 5

array([[False, False, False,  True,  True],
       [False, False,  True,  True,  True]])

In [4]:
new_array = np.arange(0,100,5)
new_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [5]:
new_array = new_array.reshape(4,5)
new_array

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [7]:
new_array[:,::-1]

array([[20, 15, 10,  5,  0],
       [45, 40, 35, 30, 25],
       [70, 65, 60, 55, 50],
       [95, 90, 85, 80, 75]])

In [8]:
array_a = np.arange(1,10).reshape(3,3)
array_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
array_b = np.array([[2,2,2], [3,4,5], [6,7,8]])
array_b

array([[2, 2, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
array_a.sum(axis=1), array_a.sum(axis=0)

(array([ 6, 15, 24]), array([12, 15, 18]))

In [17]:
array_a.prod(axis=1), array_a.prod(axis=0)

(array([  6, 120, 504]), array([ 28,  80, 162]))

In [20]:
array_ones = np.ones((5,5), dtype=int)
array_ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
array_num = np.array([1,2,3,4,5])
array_ones * array_num

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])