In [2]:
import numpy as np

In [3]:
random_numbers = np.random.randint(1,100,100)
random_numbers

array([58, 39, 42, 15, 12, 33, 71,  8, 23, 74, 12, 70, 59, 96, 19, 91, 11,
       80, 36, 23, 80, 13, 27, 58, 31, 86, 30, 58, 42, 89, 86, 37, 72, 83,
       26, 96, 92, 57, 95, 64, 53, 72, 45, 15, 59, 29, 51, 87, 48, 71, 45,
       46, 33,  4, 80, 32, 38, 41,  1, 37, 77, 66, 12, 99, 70, 94, 19, 82,
       74, 15, 43, 17,  2, 77, 59, 36,  5, 45, 40, 97, 10, 51, 66, 73, 82,
       68, 72,  6, 60, 41, 11, 28, 77, 51,  3, 27, 66, 15, 55, 15])

In [4]:
random_numbers.mean()

48.87

In [5]:
random_numbers.variance()

AttributeError: 'numpy.ndarray' object has no attribute 'variance'

In [13]:
numbers = np.random.randn(100)
numbers

array([ 0.14980107,  0.32688969,  0.58850824, -1.2938511 , -0.85851093,
        0.66514874, -1.90186689,  3.85138076, -1.88547692, -0.94028776,
       -0.61913703,  1.35181938,  1.2725047 ,  0.28335851,  2.25289466,
       -1.00796216, -0.27389644, -0.23101448,  0.76636656, -0.53363633,
       -0.98094802, -0.01946765, -1.14977845, -0.10342247, -0.19339296,
        0.09157513, -1.57124785, -1.10346801, -0.51419674, -0.92276989,
        0.20323831, -0.90960388, -0.87061595,  2.31697162, -0.18763693,
        0.09369112, -0.24849584, -0.78039952, -0.71666161,  1.3430733 ,
       -1.43633421, -0.25020019, -1.38647517, -0.06640779, -1.15385894,
        2.16346743,  0.1369265 , -1.93494892, -1.1174867 ,  0.79182471,
       -0.49739682, -0.22968172, -0.01435326,  1.98253449, -1.15976896,
        1.41897133, -0.01221606, -0.60548875,  0.99243293, -0.64327826,
       -1.55674458, -0.89716259,  0.51579369, -0.59785545,  0.73370323,
        0.24904119, -0.21673939,  0.21194799,  0.25133813, -0.46

In [14]:
numbers.mean(), numbers.std(), numbers.var()

(-0.14998107879623973, 1.0428522143452417, 1.087540740964774)

In [15]:
numbers = np.array([1, 2, 0.2, 0.3])
1/numbers

array([1.        , 0.5       , 5.        , 3.33333333])

In [21]:
numbers = np.array([21,80,54,65,41,81, 82,55,17,22])
numbers

array([21, 80, 54, 65, 41, 81, 82, 55, 17, 22])

In [23]:
numbers[:3].sort(), numbers

(None, array([21, 54, 80, 65, 41, 81, 82, 55, 17, 22]))

In [24]:
numbers[np.argpartition(numbers,range(3))]

array([17, 21, 22, 65, 41, 81, 82, 55, 54, 80])

In [31]:
np.random.randn(7)

array([ 0.28810712,  0.82237483,  0.22685777, -0.5942637 , -1.52752557,
       -1.54662896, -0.33475572])

In [33]:
print(np.random.normal(size=7))

[-1.41044808  0.11692809  1.04977916 -0.59867202 -0.24095064  0.34327965
 -1.34585495]


In [ ]:
random_vector = np.random.randint(10)
random_vector, 
random_vector[random_vector.argmax()] = 10

In [9]:
array = np.arange(1301,1302)

In [10]:
type(array)

numpy.ndarray

In [11]:
np.full(10,-1)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [19]:
np.ones([3,2,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [18]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   