In [2]:
import numpy as np

Write a Python program to multiply two matrices
using numpy

In [3]:
matrix_1 = np.random.randint(1,10, (3,3))
matrix_1

array([[6, 6, 3],
       [4, 6, 7],
       [3, 5, 1]])

In [4]:
matrix_2 = np.random.randint(11,20, (3,4))
matrix_2

array([[15, 12, 12, 11],
       [17, 19, 19, 13],
       [12, 11, 17, 15]])

Matrix multiplication using np.matmul

In [5]:
np.matmul(matrix_1, matrix_2)

array([[228, 219, 237, 189],
       [246, 239, 281, 227],
       [142, 142, 148, 113]])

Matrix multiplication using @

In [6]:
matrix_1@matrix_2

array([[228, 219, 237, 189],
       [246, 239, 281, 227],
       [142, 142, 148, 113]])

Matrix multiplication using dot

In [7]:
matrix_1.dot(matrix_2)

array([[228, 219, 237, 189],
       [246, 239, 281, 227],
       [142, 142, 148, 113]])

2. Write a Python program to get the floor, ceiling and
truncated values of the elements of an numpy
array

In [8]:
matrix = np.random.randn(5,5)
matrix

array([[-2.12055492, -0.73241876,  0.01584754,  1.45203095,  1.25046523],
       [-0.82521524, -2.10051465,  0.04408267, -0.28174192, -0.22323382],
       [-0.66131427,  1.01509502,  0.48954679,  1.04784084,  0.91049017],
       [-0.47431118, -1.51194856, -1.94723102,  0.71360606, -0.39239199],
       [ 0.14187421, -1.7291212 ,  0.36715612, -0.34968465, -0.67111485]])

In [9]:
np.floor(matrix)

array([[-3., -1.,  0.,  1.,  1.],
       [-1., -3.,  0., -1., -1.],
       [-1.,  1.,  0.,  1.,  0.],
       [-1., -2., -2.,  0., -1.],
       [ 0., -2.,  0., -1., -1.]])

In [10]:
np.ceil(matrix)

array([[-2., -0.,  1.,  2.,  2.],
       [-0., -2.,  1., -0., -0.],
       [-0.,  2.,  1.,  2.,  1.],
       [-0., -1., -1.,  1., -0.],
       [ 1., -1.,  1., -0., -0.]])

In [11]:
np.round(matrix)

array([[-2., -1.,  0.,  1.,  1.],
       [-1., -2.,  0., -0., -0.],
       [-1.,  1.,  0.,  1.,  1.],
       [-0., -2., -2.,  1., -0.],
       [ 0., -2.,  0., -0., -1.]])

In [12]:
np.trunc(matrix)

array([[-2., -0.,  0.,  1.,  1.],
       [-0., -2.,  0., -0., -0.],
       [-0.,  1.,  0.,  1.,  0.],
       [-0., -1., -1.,  0., -0.],
       [ 0., -1.,  0., -0., -0.]])

3. Write a Python program to find the inverse of a
matrix.

In [13]:
matrix = np.random.randint(1,5, (3,3))
matrix

array([[4, 4, 1],
       [2, 3, 1],
       [2, 3, 4]])

In [14]:
matrix_inv = np.linalg.inv(matrix)
matrix_inv

array([[ 0.75      , -1.08333333,  0.08333333],
       [-0.5       ,  1.16666667, -0.16666667],
       [ 0.        , -0.33333333,  0.33333333]])

In [17]:
matrix@matrix_inv

array([[ 1.00000000e+00, -2.77555756e-16,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

4. Write a Python program to perform addition,
subtraction, multiplication and divsion on the given
polynomials.

In [16]:
vector_a = np.random.randint(1,10, (1,5))
vector_a

array([[7, 5, 1, 1, 5]])

In [15]:
vector_b = np.random.randint(1,10, (1,5))
vector_b

array([[2, 2, 4, 8, 6]])

In [18]:
add = vector_a + vector_b
add

array([[ 9,  7,  5,  9, 11]])

In [21]:
sub = vector_a - vector_b
sub

array([[ 5,  3, -3, -7, -1]])

In [19]:
mul = vector_a * vector_b
mul

array([[14, 10,  4,  8, 30]])

In [20]:
div = vector_a/vector_b
div

array([[3.5       , 2.5       , 0.25      , 0.125     , 0.83333333]])

5. Write a Python program to create a random array
with N elements and compute the average, variance,
standard deviation of the array elements.

In [22]:
array = np.random.randint(1,100, (1,10))
array

array([[36, 13, 46, 31,  5,  8, 75, 63, 98, 58]])

In [23]:
array.mean(), array.std(), array.var()

(43.3, 29.058733626914993, 844.4100000000001)

6. Write a Python program to compute the reciprocal for
all elements in a given array.

In [25]:
array = np.array([1. ,2. ,0.2 ,0.3])
array

array([1. , 2. , 0.2, 0.3])

In [24]:
print("reciprocal:", 1/array)

reciprocal: [[0.02777778 0.07692308 0.02173913 0.03225806 0.2        0.125
  0.01333333 0.01587302 0.01020408 0.01724138]]


7. Write a Python program to sort the specified number
of elements from beginning of a given array.

In [ ]:
array = np.random.randint(1,100, (1,20))
array

In [27]:
parray= np.argpartition(array, range(3))
parray
#help(np.argpartition)

array([2, 3, 0, 1], dtype=int64)

9. Write a Python program to create random vector of
size N and replace the maximum value by N.

In [28]:
random_vector = np.random.randint(1,100, 10)
random_vector

array([96, 79, 67, 60, 11, 45, 80, 48, 83, 82])

In [29]:
N = -1
N

-1

In [30]:
random_vector.max(), random_vector.argmax()

(96, 0)

In [31]:
random_vector[random_vector.argmax()] = N
random_vector

array([-1, 79, 67, 60, 11, 45, 80, 48, 83, 82])

10. Write a Python program to find the most frequent
value in an array.

In [32]:
array = np.random.randint(1,5, 10)
array

array([3, 2, 4, 3, 1, 3, 4, 4, 2, 3])

In [33]:
array.sort()
array

array([1, 2, 2, 3, 3, 3, 3, 4, 4, 4])

In [49]:
array = np.array([9,4,6,8,4,0,4,8,5,7,2,5,2,0,0,2,8,9,4,5,2,5,6,5,3,6,8,8,8,9,9,2,7,6,2,1,8
,8,4,4])

In [50]:
previous_number = array[0]
current_number = -1
previous_counter = 1
current_counter = 1
for i in range(0,len(array)):
    if array[i] == array[i-1]:
        current_counter += 1
    else:
        if current_counter > previous_counter:
            previous_number = array[i-1]
            previous_counter = current_counter
        current_counter = 1
    current_number = array[i]

if current_counter > previous_counter:
    previous_number = array[i-1]
    previous_counter = current_counter

previous_number, previous_counter

(8, 3)

In [53]:
array = np.array([9,4,6,8,4,0,4,8,5,7,2,5,2,0,0,0,0,0,0,0,0,0,0,0,0,2,8,9,4,5,2,5,6,5,3,6,8,8,9,9,2,7,6,2,1,8
,8,4,4])
array.sort()
print(array)
print(np.bincount(array))
print(np.bincount(array).argmax())
#help(np.bincount)

[0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 2 2 2 2 2 3 4 4 4 4 4 4 5 5 5 5 5 6 6 6 6 7
 7 8 8 8 8 8 8 8 9 9 9 9]
[13  1  6  1  6  5  4  2  7  4]
0


13. Write a NumPy program to create a 3x3x3 array with
random values.

In [54]:
np.random.randint(1,10, (3,3,3))

array([[[6, 2, 1],
        [1, 6, 1],
        [1, 8, 7]],

       [[8, 1, 7],
        [2, 9, 1],
        [7, 2, 8]],

       [[5, 1, 9],
        [7, 6, 3],
        [3, 9, 3]]])

14. Write a Python program to find point by point
distances of a random vector with shape (J,K)
representing coordinates.

No Idea

15. Write a NumPy program to check if each element of
a given array is composed of digits only, lower case
letters only and upper case letters only

In [57]:
array = np.array(['Python','PHP','JS','Examples','html5','5'])
array

array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype='<U8')

In [69]:
is_digit = [a.isdigit() for a in array]
print(is_digit)
is_lower = [a.islower() for a in array]
print(is_lower)
is_upper = [a.isupper() for a in array]
print(is_upper)

[False, False, False, False, False, True]
[False, False, False, False, True, False]
[False, True, True, False, False, False]


16. Write a Python program to Triangulate a location
based on co-ordinates.

In [70]:
array = np.array([20.0497520, 31.39864012947, 12.30974023])
array.mean()

21.25271078649

17. Write a Python program to evaluate Einstein’s
summation convention of two given multidimensional
arrays.

No Idea

18. Write a Python code to determine the rank of the
matrix.

In [73]:
matrix = np.array([[1,3,7],[2,8,3],[7,8,1]])
np.linalg.matrix_rank(matrix)

3