In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, RobustScaler, MinMaxScaler

In [2]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
le = LabelEncoder()
le.fit(array)
result = le.transform(array)

In [4]:
result

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [5]:
le.fit_transform(array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [6]:
arrary_2d = result.reshape(len(array),1)
arrary_2d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]], dtype=int64)

In [8]:
ohe = OneHotEncoder(sparse=False)
ohe.fit_transform(arrary_2d)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
from sklearn.impute import SimpleImputer

In [11]:
items = [1, 'Test', np.nan, 2, 'What']

In [12]:
df = pd.DataFrame(items, index=[0,1,2,3,4], columns=['Name'])
df

Name
0     1
1  Test
2   NaN
3     2
4  What

In [13]:
si = SimpleImputer(fill_value='Mean', strategy='constant')
si.fit(df)
si.transform(df.values)

array([[1],
       ['Test'],
       ['Mean'],
       [2],
       ['What']], dtype=object)

In [14]:
numbers = [1,np.nan,2,np.nan,3,np.nan,4,np.nan,100,np.nan,1000,np.nan,10000]
df = pd.DataFrame(numbers, columns=['Name'])
df

Name
0       1.0
1       NaN
2       2.0
3       NaN
4       3.0
5       NaN
6       4.0
7       NaN
8     100.0
9       NaN
10   1000.0
11      NaN
12  10000.0

In [19]:
si = SimpleImputer(strategy='mean',)
si.fit(df)
result = si.transform(df.values)

In [20]:
result

array([[1.00000000e+00],
       [1.58714286e+03],
       [2.00000000e+00],
       [1.58714286e+03],
       [3.00000000e+00],
       [1.58714286e+03],
       [4.00000000e+00],
       [1.58714286e+03],
       [1.00000000e+02],
       [1.58714286e+03],
       [1.00000000e+03],
       [1.58714286e+03],
       [1.00000000e+04]])

In [22]:
result = result.astype(int)
result

array([[    1],
       [ 1587],
       [    2],
       [ 1587],
       [    3],
       [ 1587],
       [    4],
       [ 1587],
       [  100],
       [ 1587],
       [ 1000],
       [ 1587],
       [10000]])

In [33]:
pd.concat([df, pd.get_dummies(data=df,columns=['Name'],dummy_na=0)],axis=1)

Name  Name_1.0  Name_2.0  Name_3.0  Name_4.0  Name_100.0  Name_1000.0  \
0       1.0         1         0         0         0           0            0   
1       NaN         0         0         0         0           0            0   
2       2.0         0         1         0         0           0            0   
3       NaN         0         0         0         0           0            0   
4       3.0         0         0         1         0           0            0   
5       NaN         0         0         0         0           0            0   
6       4.0         0         0         0         1           0            0   
7       NaN         0         0         0         0           0            0   
8     100.0         0         0         0         0           1            0   
9       NaN         0         0         0         0           0            0   
10   1000.0         0         0         0         0           0            1   
11      NaN         0         0         0         0           0            0   
12  10000.0         0         0         0         0           0            0   

    Name_10000.0  
0              0  
1              0  
2              0  
3              0  
4              0  
5              0  
6              0  
7              0  
8              0  
9              0  
10             0  
11             0  
12             1

In [38]:
mas = MinMaxScaler()
mas.fit_transform(df)

array([[0.00000000e+00],
       [           nan],
       [1.00010001e-04],
       [           nan],
       [2.00020002e-04],
       [           nan],
       [3.00030003e-04],
       [           nan],
       [9.90099010e-03],
       [           nan],
       [9.99099910e-02],
       [           nan],
       [1.00000000e+00]])

In [39]:
rs = RobustScaler()
rs.fit_transform(df)

array([[-5.47945205e-03],
       [            nan],
       [-3.65296804e-03],
       [            nan],
       [-1.82648402e-03],
       [            nan],
       [ 0.00000000e+00],
       [            nan],
       [ 1.75342466e-01],
       [            nan],
       [ 1.81917808e+00],
       [            nan],
       [ 1.82575342e+01]])

In [42]:
help(OneHotEncoder)

Help on class OneHotEncoder in module sklearn.preprocessing._encoders:

class OneHotEncoder(_BaseEncoder)
 |  OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error')
 |  
 |  Encode categorical features as a one-hot numeric array.
 |  
 |  The input to this transformer should be an array-like of integers or
 |  strings, denoting the values taken on by categorical (discrete) features.
 |  The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
 |  encoding scheme. This creates a binary column for each category and
 |  returns a sparse matrix or dense array (depending on the ``sparse``
 |  parameter)
 |  
 |  By default, the encoder derives the categories based on the unique values
 |  in each feature. Alternatively, you can also specify the `categories`
 |  manually.
 |  
 |  This encoding is needed for feeding categorical data to many scikit-learn
 |  estimators, notably linear models and SVMs with the standard ker

In [55]:
X=[['a'],['b'],['c'],['d']]
ohe = OneHotEncoder(sparse=False)
ohe.fit(X)

OneHotEncoder(sparse=False)

In [58]:
ohe.transform([['a','b']])

ValueError: The number of features in X is different to the number of features of the fitted data. The fitted data had 1 features and the X has 2 features.

In [47]:
ohe.transform([['Male']])

array([[0., 1.]])

In [51]:
np.char.

TypeError: descriptor 'tolist' of 'numpy.ndarray' object needs an argument