In [1]:
import numpy as np
import pandas as pd

### 21. Implement OneHotEncoder from sklearn to convert categorical data into numerically parsable data.

In [2]:
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
df = pd.DataFrame(data,columns=['weather'])
df

weather
0    cold
1    cold
2    warm
3    cold
4     hot
5     hot
6    warm
7    cold
8    warm
9     hot

In [18]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
ohe = OneHotEncoder(sparse=False)
le = LabelEncoder()

In [19]:
int_encoded = le.fit_transform(data)
int_encoded

array([0, 0, 2, 0, 1, 1, 2, 0, 2, 1], dtype=int64)

In [20]:
int_encoded_reshaped = int_encoded.reshape(len(int_encoded),1)
int_encoded_reshaped

array([[0],
       [0],
       [2],
       [0],
       [1],
       [1],
       [2],
       [0],
       [2],
       [1]], dtype=int64)

In [21]:
ohe.fit_transform(int_encoded_reshaped)

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

### 22. Implement a pythonic code to standardize the data given as input and the display the standardized data.

In [22]:
X=[[10],[15],[22],[33],[25],[34],[56]]
Y=[[101],[105],[222],[333],[225],[334],[556]]

In [25]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit_transform(X)

array([[-1.27049317],
       [-0.91475508],
       [-0.41672176],
       [ 0.36590203],
       [-0.20327891],
       [ 0.43704965],
       [ 2.00229723]])

In [26]:
ss.fit_transform(Y)

array([[-1.14102498],
       [-1.11369504],
       [-0.31429431],
       [ 0.44411152],
       [-0.29379685],
       [ 0.450944  ],
       [ 1.96775565]])

### 23. Write a Python code to utilise the MinMax Scaler method to reiterate all values in a provided range.

In [27]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
mms.fit_transform(X)

array([[0.        ],
       [0.10869565],
       [0.26086957],
       [0.5       ],
       [0.32608696],
       [0.52173913],
       [1.        ]])

In [28]:
mms.fit_transform(Y)

array([[0.        ],
       [0.00879121],
       [0.26593407],
       [0.50989011],
       [0.27252747],
       [0.51208791],
       [1.        ]])

In [32]:
data = np.array([[-117.3],
 [27.5], 
 [0],
 [-20.9],
 [1000]])
mms = MinMaxScaler(feature_range=(1,2))
mms.fit_transform(data)

array([[1.        ],
       [1.12959814],
       [1.10498523],
       [1.08627942],
       [2.        ]])

### 24. Implement a python code such that you convert numerical array into an array with numbers in the interqaurtile range.

In [34]:
data = np.array([[-101.3],
 [27.5], 
 [1],
 [-200.9],
 [1000]])

In [36]:
from sklearn.preprocessing import RobustScaler
rs = RobustScaler()
rs.fit_transform(data)

array([[-0.79425466],
       [ 0.20574534],
       [ 0.        ],
       [-1.56754658],
       [ 7.75621118]])

### 25. Write a pythonic code to normalize the arrays/data provided by the user.

In [37]:
data = np.array(
 [[5.1,3.5,1.4,0.2],
 [4.9,3.0,1.4,0.2],
 [4.7,3.2,1.3,0.2],
 [4.6,3.1,1.5,0.2],
 [5.0,3.6,1.4,0.2]])

In [38]:
from sklearn.preprocessing import normalize
normalize(data)

array([[0.80377277, 0.55160877, 0.22064351, 0.0315205 ],
       [0.82813287, 0.50702013, 0.23660939, 0.03380134],
       [0.80533308, 0.54831188, 0.2227517 , 0.03426949],
       [0.80003025, 0.53915082, 0.26087943, 0.03478392],
       [0.790965  , 0.5694948 , 0.2214702 , 0.0316386 ]])

### 26. Develop a python code to generate sample data out of existing data and append it to the dataset.

In [41]:
df = pd.read_csv('lap_times.csv')
df.head()

raceId  driverId  lap  position      time  milliseconds
0     841        20    1         1  1:38.109         98109
1     841        20    2         1  1:33.006         93006
2     841        20    3         1  1:32.713         92713
3     841        20    4         1  1:32.803         92803
4     841        20    5         1  1:32.342         92342

In [46]:
df.iloc[:100].sample(frac=0.25).shape

(25, 6)

In [55]:
df.filter(regex='p').head(1)

lap  position
0    1         1

### 27. Use filter() function to subset all columns in a dataframe which has the letter provided by user in its name.

### 28. Develop a Pythonic code to generate sample data and replace all the null values with dummy data.

In [ ]:
df.head().apply(lambda x: x.mean())

In [ ]:
df.head()