In [1]:
import numpy as np

Create an array

In [2]:
array = np.array([1,2,3,4])
array

array([1, 2, 3, 4])

Find the mean 

np.mean(array)

Find the square root 

In [4]:
np.sqrt(4)

2.0

Get linearly spaced array

In [5]:
array = np.linspace(1,10, 8)
array

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

Create a list of 15 numbers from 4 to 100

In [6]:
array = np.linspace(4, 100, 15)
array

array([  4.        ,  10.85714286,  17.71428571,  24.57142857,
        31.42857143,  38.28571429,  45.14285714,  52.        ,
        58.85714286,  65.71428571,  72.57142857,  79.42857143,
        86.28571429,  93.14285714, 100.        ])

In [8]:
rounded_array = np.round(array)
rounded_array

array([  4.,  11.,  18.,  25.,  31.,  38.,  45.,  52.,  59.,  66.,  73.,
        79.,  86.,  93., 100.])

In [9]:
square_root = np.sqrt(rounded_array)
square_root

array([ 2.        ,  3.31662479,  4.24264069,  5.        ,  5.56776436,
        6.164414  ,  6.70820393,  7.21110255,  7.68114575,  8.1240384 ,
        8.54400375,  8.88819442,  9.2736185 ,  9.64365076, 10.        ])