In [1]:
import numpy as np

In [40]:
no_of_movies = 20
no_of_users = 10

In [34]:
movies = np.arange(no_of_movies)
movies[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
users = np.arange(no_of_users)
users[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
movie_ratings = []
for user in range(no_of_users):
    user_ratings = np.full(no_of_movies, 0)
    #print("user_ratings: ", user_ratings)
    no_of_movies_rated = np.random.randint(0,no_of_movies)
    #print("no_of_movies_rated:", no_of_movies_rated)
    movie_rating = [np.random.randint(no_of_movies) for i in range(no_of_movies_rated)]
    #print("movie_ratings: ", movie_ratings)
    for rating in movie_rating:
        user_ratings[rating] = np.random.randint(1, 10)
    movie_ratings.append(list(user_ratings))
movie_ratings = np.array(movie_ratings)
movie_ratings

array([[0, 0, 6, 0, 0, 0, 0, 0, 0, 5, 0, 8, 2, 1, 0, 0, 2, 0, 8, 2],
       [0, 0, 0, 6, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 5, 4, 5, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 5, 4, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [5, 1, 0, 0, 9, 6, 0, 0, 6, 5, 0, 9, 1, 0, 1, 1, 0, 6, 0, 0],
       [0, 6, 4, 0, 0, 0, 0, 5, 9, 1, 0, 2, 7, 5, 6, 0, 0, 5, 6, 0],
       [0, 0, 0, 9, 0, 6, 6, 1, 1, 0, 9, 0, 0, 0, 0, 2, 4, 6, 4, 3],
       [9, 6, 8, 2, 0, 0, 1, 2, 0, 1, 6, 0, 3, 0, 0, 7, 0, 0, 0, 0],
       [0, 0, 9, 0, 8, 0, 0, 0, 6, 0, 0, 4, 5, 8, 0, 0, 9, 1, 7, 5]])

In [49]:
no_of_expert_ratings = 2
no_of_additional_movies = 5

In [50]:
expert_movie_ratings = []
for i in range(no_of_expert_ratings):
    user_ratings = np.full(no_of_movies, 0)
    no_of_movies_rated = np.random.randint(0,no_of_movies)
    movie_rating = [np.random.randint(no_of_movies) for i in range(no_of_movies_rated)]
    for rating in movie_rating:
        user_ratings[rating] = np.random.randint(1, 10)
    expert_movie_ratings.append(list(user_ratings))
expert_movie_ratings = np.array(expert_movie_ratings)
expert_movie_ratings

array([[0, 0, 9, 9, 0, 2, 0, 0, 0, 4, 1, 9, 0, 0, 0, 0, 2, 8, 6, 0],
       [7, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 9, 0]])

In [51]:
user_expert_movie_ratings = np.vstack([movie_ratings, expert_movie_ratings])
user_expert_movie_ratings

array([[0, 0, 6, 0, 0, 0, 0, 0, 0, 5, 0, 8, 2, 1, 0, 0, 2, 0, 8, 2],
       [0, 0, 0, 6, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 5, 4, 5, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 5, 4, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [5, 1, 0, 0, 9, 6, 0, 0, 6, 5, 0, 9, 1, 0, 1, 1, 0, 6, 0, 0],
       [0, 6, 4, 0, 0, 0, 0, 5, 9, 1, 0, 2, 7, 5, 6, 0, 0, 5, 6, 0],
       [0, 0, 0, 9, 0, 6, 6, 1, 1, 0, 9, 0, 0, 0, 0, 2, 4, 6, 4, 3],
       [9, 6, 8, 2, 0, 0, 1, 2, 0, 1, 6, 0, 3, 0, 0, 7, 0, 0, 0, 0],
       [0, 0, 9, 0, 8, 0, 0, 0, 6, 0, 0, 4, 5, 8, 0, 0, 9, 1, 7, 5],
       [0, 0, 9, 9, 0, 2, 0, 0, 0, 4, 1, 9, 0, 0, 0, 0, 2, 8, 6, 0],
       [7, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 9, 0]])

In [55]:
no_of_new_movies = 5
new_movie_ratings = []
for user in range(no_of_users+no_of_expert_ratings):
    user_ratings = np.full(no_of_new_movies, 0)
    #print("user_ratings: ", user_ratings)
    no_of_movies_rated = np.random.randint(0,no_of_new_movies)
    #print("no_of_movies_rated:", no_of_movies_rated)
    movie_rating = [np.random.randint(no_of_new_movies) for i in range(no_of_movies_rated)]
    #print("movie_ratings: ", movie_ratings)
    for rating in movie_rating:
        user_ratings[rating] = np.random.randint(1, 10)
    new_movie_ratings.append(list(user_ratings))
new_movie_ratings = np.array(new_movie_ratings)
new_movie_ratings, new_movie_ratings.shape

(array([[7, 0, 0, 1, 0],
        [0, 0, 0, 1, 3],
        [8, 5, 8, 0, 1],
        [0, 7, 8, 0, 7],
        [0, 0, 9, 0, 0],
        [0, 0, 8, 2, 0],
        [0, 0, 0, 0, 0],
        [6, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [9, 7, 7, 0, 0],
        [0, 0, 0, 0, 0],
        [6, 0, 0, 0, 0]]), (12, 5))

In [58]:
total_movie_ratings = np.hstack([user_expert_movie_ratings, new_movie_ratings])
total_movie_ratings[:10,:10]

array([[0, 0, 6, 0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 6, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 8, 5, 4, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [5, 1, 0, 0, 9, 6, 0, 0, 6, 5],
       [0, 6, 4, 0, 0, 0, 0, 5, 9, 1],
       [0, 0, 0, 9, 0, 6, 6, 1, 1, 0],
       [9, 6, 8, 2, 0, 0, 1, 2, 0, 1],
       [0, 0, 9, 0, 8, 0, 0, 0, 6, 0]])

In [74]:
print('mean:', np.mean(total_movie_ratings, axis=0))
print('median:', np.median(total_movie_ratings, axis=0))
print('std:', np.std(total_movie_ratings, axis=0))
print('min:', np.min(total_movie_ratings, axis=0))
print('max:', np.max(total_movie_ratings, axis=0))

mean: [1.75       1.08333333 3.66666667 2.58333333 1.91666667 2.
 1.08333333 0.66666667 1.83333333 1.33333333 1.33333333 3.16666667
 1.58333333 1.83333333 1.         1.83333333 1.91666667 2.16666667
 3.33333333 0.83333333 3.         1.58333333 3.33333333 0.41666667
 0.91666667]
median: [0.  0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.5 0.  0.  0.  0.5 0.
 2.  0.  0.  0.  0.  0.  0. ]
std: [3.1391347  2.2157893  3.88014891 3.4990078  3.17433283 2.82842712
 2.01900691 1.43372088 3.07769755 1.97202659 2.83823106 3.67045259
 2.2157893  3.07769755 2.04124145 2.79384244 2.69129254 2.96741564
 3.51978535 1.57233019 3.62859018 2.78263464 3.96512575 0.64009548
 2.01900691]
min: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
max: [9 6 9 9 9 8 6 5 9 5 9 9 7 8 6 8 9 8 9 5 9 7 9 2 7]


In [71]:
#help(np.where)
np.where(total_movie_ratings>0, total_movie_ratings, -10)

array([[-10, -10,   6, -10, -10, -10, -10, -10, -10,   5, -10,   8,   2,
          1, -10, -10,   2, -10,   8,   2,   7, -10, -10,   1, -10],
       [-10, -10, -10,   6, -10, -10,   5, -10, -10, -10, -10, -10, -10,
        -10,   5,   4,   5, -10, -10, -10, -10, -10, -10,   1,   3],
       [-10, -10, -10, -10,   2, -10, -10, -10, -10, -10, -10, -10,   1,
        -10, -10, -10, -10, -10, -10, -10,   8,   5,   8, -10,   1],
       [-10, -10,   8,   5,   4,   8, -10, -10, -10, -10, -10,   6, -10,
          8, -10,   8, -10, -10, -10, -10, -10,   7,   8, -10,   7],
       [-10, -10, -10, -10, -10, -10,   1, -10, -10, -10, -10, -10, -10,
        -10, -10, -10, -10, -10, -10, -10, -10, -10,   9, -10, -10],
       [  5,   1, -10, -10,   9,   6, -10, -10,   6,   5, -10,   9,   1,
        -10,   1,   1, -10,   6, -10, -10, -10, -10,   8,   2, -10],
       [-10,   6,   4, -10, -10, -10, -10,   5,   9,   1, -10,   2,   7,
          5,   6, -10, -10,   5,   6, -10, -10, -10, -10, -10, -10],
      