In [1]:
import numpy as np

Write a Python program to multiply two matrices
using numpy

In [2]:
matrix_1 = np.random.randint(1,10, (3,3))
matrix_1

array([[3, 1, 2],
       [6, 7, 6],
       [2, 4, 6]])

In [3]:
matrix_2 = np.random.randint(11,20, (3,4))
matrix_2

array([[18, 13, 16, 18],
       [17, 15, 11, 13],
       [15, 18, 17, 11]])

Matrix multiplication using np.matmul

In [4]:
np.matmul(matrix_1, matrix_2)

array([[101,  90,  93,  89],
       [317, 291, 275, 265],
       [194, 194, 178, 154]])

Matrix multiplication using @

In [5]:
matrix_1@matrix_2

array([[101,  90,  93,  89],
       [317, 291, 275, 265],
       [194, 194, 178, 154]])

Matrix multiplication using dot

In [8]:
matrix_1.dot(matrix_2)

array([[101,  90,  93,  89],
       [317, 291, 275, 265],
       [194, 194, 178, 154]])

2. Write a Python program to get the floor, ceiling and
truncated values of the elements of an numpy
array

In [9]:
matrix = np.random.randn(5,5)
matrix

array([[-0.09625829, -0.26438727,  0.38145564,  1.40940129, -0.3532835 ],
       [-0.0185279 , -0.55636436, -1.30866011, -0.54529089, -0.47685933],
       [-0.05805574,  0.38650953, -2.37699874,  1.25957405,  0.65404417],
       [-1.26354609, -1.13680041,  1.56301551,  2.02561639,  1.886907  ],
       [-0.08180372, -0.08789427, -0.94083334,  1.1442078 ,  0.42593535]])

In [11]:
np.floor(matrix)

array([[-1., -1.,  0.,  1., -1.],
       [-1., -1., -2., -1., -1.],
       [-1.,  0., -3.,  1.,  0.],
       [-2., -2.,  1.,  2.,  1.],
       [-1., -1., -1.,  1.,  0.]])

In [12]:
np.ceil(matrix)

array([[-0., -0.,  1.,  2., -0.],
       [-0., -0., -1., -0., -0.],
       [-0.,  1., -2.,  2.,  1.],
       [-1., -1.,  2.,  3.,  2.],
       [-0., -0., -0.,  2.,  1.]])

In [13]:
np.round(matrix)

array([[-0., -0.,  0.,  1., -0.],
       [-0., -1., -1., -1., -0.],
       [-0.,  0., -2.,  1.,  1.],
       [-1., -1.,  2.,  2.,  2.],
       [-0., -0., -1.,  1.,  0.]])

In [14]:
np.trunc(matrix)

array([[-0., -0.,  0.,  1., -0.],
       [-0., -0., -1., -0., -0.],
       [-0.,  0., -2.,  1.,  0.],
       [-1., -1.,  1.,  2.,  1.],
       [-0., -0., -0.,  1.,  0.]])

3. Write a Python program to find the inverse of a
matrix.

In [19]:
matrix = np.random.randint(1,5, (3,3))
matrix

array([[3, 2, 1],
       [2, 2, 1],
       [1, 1, 4]])

In [20]:
matrix_inv = np.linalg.inv(matrix)
matrix_inv

array([[ 1.        , -1.        ,  0.        ],
       [-1.        ,  1.57142857, -0.14285714],
       [ 0.        , -0.14285714,  0.28571429]])

In [21]:
matrix@matrix_inv

array([[1.00000000e+00, 3.88578059e-16, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

4. Write a Python program to perform addition,
subtraction, multiplication and divsion on the given
polynomials.

In [22]:
vector_a = np.random.randint(1,10, (1,5))
vector_a

array([[3, 1, 3, 4, 5]])

In [23]:
vector_b = np.random.randint(1,10, (1,5))
vector_b

array([[3, 9, 1, 4, 4]])

In [25]:
add = vector_a + vector_b
add

array([[ 6, 10,  4,  8,  9]])

In [26]:
sub = vector_a - vector_b
sub

array([[ 0, -8,  2,  0,  1]])

In [27]:
mul = vector_a * vector_b
mul

array([[ 9,  9,  3, 16, 20]])

In [28]:
div = vector_a/vector_b
div

array([[1.        , 0.11111111, 3.        , 1.        , 1.25      ]])

5. Write a Python program to create a random array
with N elements and compute the average, variance,
standard deviation of the array elements.

In [32]:
array = np.random.randint(1,100, (1,10))
array

array([[87, 95, 46, 44, 66, 82, 20, 85, 84,  8]])

In [41]:
array.mean(), array.std(), array.var()

(61.7, 28.986376110165963, 840.21)

6. Write a Python program to compute the reciprocal for
all elements in a given array.

In [43]:
array = np.array([1. ,2. ,0.2 ,0.3])
array

array([1. , 2. , 0.2, 0.3])

In [44]:
print("reciprocal:", 1/array)

reciprocal: [1.         0.5        5.         3.33333333]


7. Write a Python program to sort the specified number
of elements from beginning of a given array.

In [46]:
array = np.random.randint(1,100, (1,20))
array

array([[49, 47, 48, 88, 63, 72, 67, 83,  3, 19, 91,  6, 76, 14, 24, 83,
        28, 29, 66, 27]])

In [51]:
parray= np.argpartition(array, range(3), axis=1)
parray
#help(np.argpartition)

array([[ 8, 11, 13,  3,  4,  5,  6,  7,  0,  9, 10,  1, 12,  2, 14, 15,
        16, 17, 18, 19]], dtype=int64)

9. Write a Python program to create random vector of
size N and replace the maximum value by N.

In [59]:
random_vector = np.random.randint(1,100, 10)
random_vector

array([76, 60, 47, 96, 46, 76, 86, 65, 99,  7])

In [60]:
N = -1
N

-1

In [61]:
random_vector.max(), random_vector.argmax()

(99, 8)

In [62]:
random_vector[random_vector.argmax()] = N
random_vector

array([76, 60, 47, 96, 46, 76, 86, 65, -1,  7])

10. Write a Python program to find the most frequent
value in an array.

In [63]:
array = np.random.randint(1,5, 10)
array

array([2, 2, 4, 1, 1, 1, 1, 2, 4, 3])

In [73]:
array.sort()
array

array([1, 1, 1, 1, 2, 2, 2, 3, 4, 4])

In [91]:
array = np.array([1,1,1,1,2,2,2,2,3,4,4,4,4,4])

In [93]:
previous_number = array[0]
current_number = -1
previous_counter = 1
current_counter = 1
for i in range(0,len(array)):
    if array[i] == array[i-1]:
        current_counter += 1
    else:
        if current_counter > previous_counter:
            previous_number = array[i-1]
            previous_counter = current_counter
        current_counter = 1
    current_number = array[i]

if current_counter > previous_counter:
    previous_number = array[i-1]
    previous_counter = current_counter

previous_number, previous_counter

(4, 5)

In [79]:
array

array([1, 1, 1, 1, 2, 2, 2, 3, 4, 4])

In [71]:
np.linalg.linalg.

AttributeError: module 'numpy.linalg' has no attribute 'mode'