In [2]:
import numpy as np

Write a program to find the most frequent value in an array.

In [3]:
array = np.random.randint(1,10,20)
array

array([5, 4, 6, 1, 6, 2, 6, 1, 5, 6, 4, 8, 4, 9, 8, 1, 2, 8, 5, 1])

In [11]:
np.bincount(array).argmax()

1

Write a program to create a 3*3*3 matrix with random values

In [20]:
array = np.random.rand(3,3,3)
array

array([[[0.94006101, 0.55671547, 0.02476187],
        [0.48434876, 0.04744294, 0.79901148],
        [0.92632214, 0.73625551, 0.15858588]],

       [[0.58522044, 0.84296532, 0.97473331],
        [0.69504772, 0.03268923, 0.27109117],
        [0.19011448, 0.77701771, 0.93317503]],

       [[0.79165451, 0.80210491, 0.61023141],
        [0.46149479, 0.55799225, 0.69814417],
        [0.13679303, 0.55841964, 0.2149473 ]]])

help(np.random.rand)

Write a program to check if each element of a given array is composed of digits only, lower case letters only and upper case letters only.

In [22]:
array = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'])
array

array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype='<U8')

In [26]:
np.char.isdigit(array)

array([False, False, False, False, False,  True])

In [27]:
np.char.isalpha(array)

array([ True,  True,  True,  True, False, False])

In [28]:
np.char.islower(array)

array([False, False, False, False,  True, False])

Write a program to triangulate a location based on co-ordinates

In [29]:
array = np.array([20.0497520, 31.39864012947, 12.30974023])
array

array([20.049752  , 31.39864013, 12.30974023])

In [30]:
array.mean()

21.25271078649

Write a program to determine the rank of the matrix

In [31]:
array = np.array([[1,3,7], [2,8,3], [7,8,1]])
array

array([[1, 3, 7],
       [2, 8, 3],
       [7, 8, 1]])

In [33]:
array.rank

AttributeError: 'numpy.ndarray' object has no attribute 'rank'

In [35]:
np.linalg.matrix_rank(array)

3

Write a NumPy program to multiply a MxN matrix by a NxA matrix and create a real matrix product

In [42]:
array_5_3 = np.array([[0.94293584, 0.8091474, 0.72330868],
 [0.91143684, 0.54976631, 0.37547562],
 [0.3656866 ,0.94185543 ,0.98414967],
 [0.81470666, 0.80629404, 0.46326721],
 [0.40648925, 0.70615124, 0.4786933 ]])
array_5_3

array([[0.94293584, 0.8091474 , 0.72330868],
       [0.91143684, 0.54976631, 0.37547562],
       [0.3656866 , 0.94185543, 0.98414967],
       [0.81470666, 0.80629404, 0.46326721],
       [0.40648925, 0.70615124, 0.4786933 ]])

In [43]:
array_3_2 = np.array([[0.45507569, 0.53265048],
             [0.41761748, 0.87547934],
             [0.83832095, 0.79087463]])
array_3_2

array([[0.45507569, 0.53265048],
       [0.41761748, 0.87547934],
       [0.83832095, 0.79087463]])

In [45]:
array_5_3.dot(array_3_2), np.dot(array_5_3, array_3_2)

(array([[1.3733861 , 1.78269354],
        [0.95913385, 1.26374046],
        [1.38478366, 1.79769712],
        [1.09584229, 1.50623395],
        [0.8811831 , 1.2133239 ]]), array([[1.3733861 , 1.78269354],
        [0.95913385, 1.26374046],
        [1.38478366, 1.79769712],
        [1.09584229, 1.50623395],
        [0.8811831 , 1.2133239 ]]))